version: '2'
services:
  web:
    build: .
    privileged: true
    labels:
      - convox.port.443.protocol=https
    ports:
      - 443:9292
      - 9292:9292
    environment:
      - DB_URL=
      - BASE_PATH=/var/s3
